const request = require("supertest");
const app = require("../app"); //import express app


//group notifications API tests
describe("Notifications API", () => {

  //returns a user's notifications with counts
  test("returns notifications for a user", async () => {
    const response = await request(app).get("/api/notifications/user-001");

    expect(response.statusCode).toBe(200);
    expect(response.body.userId).toBe("user-001");
    expect(Array.isArray(response.body.notifications)).toBe(true);
    expect(response.body).toHaveProperty("count");
    expect(response.body).toHaveProperty("unreadCount");
    expect(response.body.notifications.every((note) => note.userId === "user-001")).toBe(true);
  });


  //notifications are sorted most recent first
  test("returns notifications sorted newest first", async () => {
    const response = await request(app).get("/api/notifications/user-001");
    const times = response.body.notifications.map((note) => new Date(note.createdAt).getTime());

    for (let i = 1; i < times.length; i++) {
      expect(times[i - 1]).toBeGreaterThanOrEqual(times[i]);
    }
  });


  //filters by unread state
  test("filters notifications by isRead", async () => {
    const response = await request(app).get("/api/notifications/user-001?isRead=false");

    expect(response.statusCode).toBe(200);
    expect(response.body.notifications.every((note) => note.isRead === false)).toBe(true);
  });


  //rejects an invalid isRead filter
  test("rejects an invalid isRead filter", async () => {
    const response = await request(app).get("/api/notifications/user-001?isRead=maybe");

    expect(response.statusCode).toBe(400);
    expect(response.body.error).toBe("isRead must be true or false.");
  });


  //returns an empty list for a user with no notifications
  test("returns an empty list for a user with no notifications", async () => {
    const response = await request(app).get("/api/notifications/nobody-here");

    expect(response.statusCode).toBe(200);
    expect(response.body.count).toBe(0);
    expect(response.body.notifications).toHaveLength(0);
  });


  //a queue join generates a retrievable notification
  test("exposes a notification generated by joining a queue", async () => {
    await request(app).post("/api/queues/svc-advising/join").send({
      userId: "notif-api-user",
      userName: "Notif API User",
    });

    const response = await request(app).get("/api/notifications/notif-api-user");

    expect(response.statusCode).toBe(200);
    const joined = response.body.notifications.find((note) => note.type === "queue-joined");
    expect(joined).toBeDefined();
    expect(joined.message).toContain("Academic Advising");
  });

});
